/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as LedgerCommitmentsRouteImport } from './routes/ledger/commitments'
import { Route as LedgerHistoryRouteImport } from './routes/ledger/history'
import { Route as LedgerInsightsRouteImport } from './routes/ledger/insights'
import { Route as LedgerTodayRouteImport } from './routes/ledger/today'
import { Route as StrideAchievementsRouteImport } from './routes/stride/achievements'
import { Route as StrideArchiveRouteImport } from './routes/stride/archive'
import { Route as StrideHistoryRouteImport } from './routes/stride/history'
import { Route as StrideInsightsRouteImport } from './routes/stride/insights'
import { Route as StrideJourneysRouteImport } from './routes/stride/journeys'
import { Route as StrideTodayRouteImport } from './routes/stride/today'
import { Route as StrideJourneysIndexRouteImport } from './routes/stride/journeys/index'
import { Route as StrideJourneysJourneyIdRouteImport } from './routes/stride/journeys/$journeyId'
import { Route as StrideJourneysNewRouteImport } from './routes/stride/journeys/new'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const LedgerCommitmentsRoute = LedgerCommitmentsRouteImport.update({
  id: '/ledger/commitments',
  path: '/ledger/commitments',
  getParentRoute: () => rootRouteImport,
} as any)
const LedgerHistoryRoute = LedgerHistoryRouteImport.update({
  id: '/ledger/history',
  path: '/ledger/history',
  getParentRoute: () => rootRouteImport,
} as any)
const LedgerInsightsRoute = LedgerInsightsRouteImport.update({
  id: '/ledger/insights',
  path: '/ledger/insights',
  getParentRoute: () => rootRouteImport,
} as any)
const LedgerTodayRoute = LedgerTodayRouteImport.update({
  id: '/ledger/today',
  path: '/ledger/today',
  getParentRoute: () => rootRouteImport,
} as any)
const StrideAchievementsRoute = StrideAchievementsRouteImport.update({
  id: '/stride/achievements',
  path: '/stride/achievements',
  getParentRoute: () => rootRouteImport,
} as any)
const StrideArchiveRoute = StrideArchiveRouteImport.update({
  id: '/stride/archive',
  path: '/stride/archive',
  getParentRoute: () => rootRouteImport,
} as any)
const StrideHistoryRoute = StrideHistoryRouteImport.update({
  id: '/stride/history',
  path: '/stride/history',
  getParentRoute: () => rootRouteImport,
} as any)
const StrideInsightsRoute = StrideInsightsRouteImport.update({
  id: '/stride/insights',
  path: '/stride/insights',
  getParentRoute: () => rootRouteImport,
} as any)
const StrideJourneysRoute = StrideJourneysRouteImport.update({
  id: '/stride/journeys',
  path: '/stride/journeys',
  getParentRoute: () => rootRouteImport,
} as any)
const StrideTodayRoute = StrideTodayRouteImport.update({
  id: '/stride/today',
  path: '/stride/today',
  getParentRoute: () => rootRouteImport,
} as any)
const StrideJourneysIndexRoute = StrideJourneysIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => StrideJourneysRoute,
} as any)
const StrideJourneysJourneyIdRoute = StrideJourneysJourneyIdRouteImport.update({
  id: '/$journeyId',
  path: '/$journeyId',
  getParentRoute: () => StrideJourneysRoute,
} as any)
const StrideJourneysNewRoute = StrideJourneysNewRouteImport.update({
  id: '/new',
  path: '/new',
  getParentRoute: () => StrideJourneysRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/ledger/commitments': typeof LedgerCommitmentsRoute
  '/ledger/history': typeof LedgerHistoryRoute
  '/ledger/insights': typeof LedgerInsightsRoute
  '/ledger/today': typeof LedgerTodayRoute
  '/stride/achievements': typeof StrideAchievementsRoute
  '/stride/archive': typeof StrideArchiveRoute
  '/stride/history': typeof StrideHistoryRoute
  '/stride/insights': typeof StrideInsightsRoute
  '/stride/journeys': typeof StrideJourneysRouteWithChildren
  '/stride/today': typeof StrideTodayRoute
  '/stride/journeys/$journeyId': typeof StrideJourneysJourneyIdRoute
  '/stride/journeys/new': typeof StrideJourneysNewRoute
  '/stride/journeys/': typeof StrideJourneysIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/ledger/commitments': typeof LedgerCommitmentsRoute
  '/ledger/history': typeof LedgerHistoryRoute
  '/ledger/insights': typeof LedgerInsightsRoute
  '/ledger/today': typeof LedgerTodayRoute
  '/stride/achievements': typeof StrideAchievementsRoute
  '/stride/archive': typeof StrideArchiveRoute
  '/stride/history': typeof StrideHistoryRoute
  '/stride/insights': typeof StrideInsightsRoute
  '/stride/today': typeof StrideTodayRoute
  '/stride/journeys/$journeyId': typeof StrideJourneysJourneyIdRoute
  '/stride/journeys/new': typeof StrideJourneysNewRoute
  '/stride/journeys': typeof StrideJourneysIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/ledger/commitments': typeof LedgerCommitmentsRoute
  '/ledger/history': typeof LedgerHistoryRoute
  '/ledger/insights': typeof LedgerInsightsRoute
  '/ledger/today': typeof LedgerTodayRoute
  '/stride/achievements': typeof StrideAchievementsRoute
  '/stride/archive': typeof StrideArchiveRoute
  '/stride/history': typeof StrideHistoryRoute
  '/stride/insights': typeof StrideInsightsRoute
  '/stride/journeys': typeof StrideJourneysRouteWithChildren
  '/stride/today': typeof StrideTodayRoute
  '/stride/journeys/$journeyId': typeof StrideJourneysJourneyIdRoute
  '/stride/journeys/new': typeof StrideJourneysNewRoute
  '/stride/journeys/': typeof StrideJourneysIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/ledger/commitments'
    | '/ledger/history'
    | '/ledger/insights'
    | '/ledger/today'
    | '/stride/achievements'
    | '/stride/archive'
    | '/stride/history'
    | '/stride/insights'
    | '/stride/journeys'
    | '/stride/today'
    | '/stride/journeys/$journeyId'
    | '/stride/journeys/new'
    | '/stride/journeys/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/ledger/commitments'
    | '/ledger/history'
    | '/ledger/insights'
    | '/ledger/today'
    | '/stride/achievements'
    | '/stride/archive'
    | '/stride/history'
    | '/stride/insights'
    | '/stride/today'
    | '/stride/journeys/$journeyId'
    | '/stride/journeys/new'
    | '/stride/journeys'
  id:
    | '__root__'
    | '/'
    | '/ledger/commitments'
    | '/ledger/history'
    | '/ledger/insights'
    | '/ledger/today'
    | '/stride/achievements'
    | '/stride/archive'
    | '/stride/history'
    | '/stride/insights'
    | '/stride/journeys'
    | '/stride/today'
    | '/stride/journeys/$journeyId'
    | '/stride/journeys/new'
    | '/stride/journeys/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  LedgerCommitmentsRoute: typeof LedgerCommitmentsRoute
  LedgerHistoryRoute: typeof LedgerHistoryRoute
  LedgerInsightsRoute: typeof LedgerInsightsRoute
  LedgerTodayRoute: typeof LedgerTodayRoute
  StrideAchievementsRoute: typeof StrideAchievementsRoute
  StrideArchiveRoute: typeof StrideArchiveRoute
  StrideHistoryRoute: typeof StrideHistoryRoute
  StrideInsightsRoute: typeof StrideInsightsRoute
  StrideJourneysRoute: typeof StrideJourneysRouteWithChildren
  StrideTodayRoute: typeof StrideTodayRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ledger/commitments': {
      id: '/ledger/commitments'
      path: '/ledger/commitments'
      fullPath: '/ledger/commitments'
      preLoaderRoute: typeof LedgerCommitmentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ledger/history': {
      id: '/ledger/history'
      path: '/ledger/history'
      fullPath: '/ledger/history'
      preLoaderRoute: typeof LedgerHistoryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ledger/insights': {
      id: '/ledger/insights'
      path: '/ledger/insights'
      fullPath: '/ledger/insights'
      preLoaderRoute: typeof LedgerInsightsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ledger/today': {
      id: '/ledger/today'
      path: '/ledger/today'
      fullPath: '/ledger/today'
      preLoaderRoute: typeof LedgerTodayRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/stride/achievements': {
      id: '/stride/achievements'
      path: '/stride/achievements'
      fullPath: '/stride/achievements'
      preLoaderRoute: typeof StrideAchievementsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/stride/archive': {
      id: '/stride/archive'
      path: '/stride/archive'
      fullPath: '/stride/archive'
      preLoaderRoute: typeof StrideArchiveRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/stride/history': {
      id: '/stride/history'
      path: '/stride/history'
      fullPath: '/stride/history'
      preLoaderRoute: typeof StrideHistoryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/stride/insights': {
      id: '/stride/insights'
      path: '/stride/insights'
      fullPath: '/stride/insights'
      preLoaderRoute: typeof StrideInsightsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/stride/journeys': {
      id: '/stride/journeys'
      path: '/stride/journeys'
      fullPath: '/stride/journeys'
      preLoaderRoute: typeof StrideJourneysRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/stride/today': {
      id: '/stride/today'
      path: '/stride/today'
      fullPath: '/stride/today'
      preLoaderRoute: typeof StrideTodayRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/stride/journeys/': {
      id: '/stride/journeys/'
      path: '/'
      fullPath: '/stride/journeys/'
      preLoaderRoute: typeof StrideJourneysIndexRouteImport
      parentRoute: typeof StrideJourneysRoute
    }
    '/stride/journeys/$journeyId': {
      id: '/stride/journeys/$journeyId'
      path: '/$journeyId'
      fullPath: '/stride/journeys/$journeyId'
      preLoaderRoute: typeof StrideJourneysJourneyIdRouteImport
      parentRoute: typeof StrideJourneysRoute
    }
    '/stride/journeys/new': {
      id: '/stride/journeys/new'
      path: '/new'
      fullPath: '/stride/journeys/new'
      preLoaderRoute: typeof StrideJourneysNewRouteImport
      parentRoute: typeof StrideJourneysRoute
    }
  }
}

interface StrideJourneysRouteChildren {
  StrideJourneysJourneyIdRoute: typeof StrideJourneysJourneyIdRoute
  StrideJourneysNewRoute: typeof StrideJourneysNewRoute
  StrideJourneysIndexRoute: typeof StrideJourneysIndexRoute
}

const StrideJourneysRouteChildren: StrideJourneysRouteChildren = {
  StrideJourneysJourneyIdRoute: StrideJourneysJourneyIdRoute,
  StrideJourneysNewRoute: StrideJourneysNewRoute,
  StrideJourneysIndexRoute: StrideJourneysIndexRoute,
}

const StrideJourneysRouteWithChildren = StrideJourneysRoute._addFileChildren(
  StrideJourneysRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  LedgerCommitmentsRoute: LedgerCommitmentsRoute,
  LedgerHistoryRoute: LedgerHistoryRoute,
  LedgerInsightsRoute: LedgerInsightsRoute,
  LedgerTodayRoute: LedgerTodayRoute,
  StrideAchievementsRoute: StrideAchievementsRoute,
  StrideArchiveRoute: StrideArchiveRoute,
  StrideHistoryRoute: StrideHistoryRoute,
  StrideInsightsRoute: StrideInsightsRoute,
  StrideJourneysRoute: StrideJourneysRouteWithChildren,
  StrideTodayRoute: StrideTodayRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
